# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('icone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rencontre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=200)),
                ('pays1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_id', to='euro.Pays')),
                ('pays2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_id', to='euro.Pays')),
            ],
        ),
    ]
