# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0003_pronostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostic',
            name='match',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='euro.Rencontre'),
            preserve_default=False,
        ),
    ]
