# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0005_auto_20160527_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencontre',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='euro.Tag'),
            preserve_default=False,
        ),
    ]
