# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0006_rencontre_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pronostic',
            name='points',
            field=models.IntegerField(default=-1),
        ),
    ]
