# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0007_auto_20160528_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronostic',
            name='score1',
            field=models.PositiveSmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='score2',
            field=models.PositiveSmallIntegerField(default=-1),
        ),
    ]
