# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0008_auto_20160529_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronostic',
            name='score1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='pronostic',
            name='score2',
            field=models.IntegerField(default=-1),
        ),
    ]
