# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0009_auto_20160529_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencontre',
            name='allowNull',
            field=models.BooleanField(default=True),
        ),
    ]
