# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0010_rencontre_allownull'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(default=-1)),
                ('score2', models.IntegerField(default=-1)),
                ('winner', models.IntegerField(default=-1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euro.Rencontre')),
            ],
        ),
    ]
