# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0013_auto_20160601_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='euro.Rencontre'),
        ),
    ]
