# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0014_auto_20160601_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencontre',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
