# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0015_auto_20160601_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
