# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0017_member_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
