# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0019_tag_sort_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('reward', models.IntegerField(default=0)),
                ('leverage', models.IntegerField(default=-1)),
                ('enddate', models.DateField()),
                ('multipleChoice', models.BooleanField(default=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euro.Rencontre')),
            ],
        ),
        migrations.CreateModel(
            name='PollChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possibleResponseText', models.CharField(blank=True, max_length=200, null=True)),
                ('possibleResponseNumber', models.IntegerField(default=-1)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euro.MatchPool')),
            ],
        ),
    ]
