# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro', '0020_matchpool_pollchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencontre',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
